name: Deploy to DigitalOcean Droplet
'on':
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone from Git REPO
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSHKEY}}
          passphrase: ${{secrets.PASSPHRASE}}
          script: |
           cd dockerized-sites
           git clone https://github.com/A3DataSolutions/KingLawWebsite.git
      - name: Build Docker Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.SSHKEY}}
          passphrase: ${{secrets.PASSPHRASE}}
          script: |
           cd dockerized-sites/KingLawWebsite
           
      

